import { Geist, Geist_Mono, Gideon_Roman } from "next/font/google";
import "./globals.css";
import Navbar from "@/Component/shared/navbar/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const GideonRoman = Gideon_Roman({
  subsets: ["latin"],
  weight: ["400"],
})
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className={`min-h-full flex flex-col ${GideonRoman .className}`}>
        <Navbar/>
        {children}
        
        </body>
    </html>
  );
}
